for_window [app_id="foot"] opacity 0.75
for_window [app_id="kitty"] opacity 0.75
for_window [app_id="eww"] corner_radius 0

layer_effects "waybar" blur enable
layer_effects "mako" blur enable; corner_radius 8
