# @gaps
#smart_gaps on
gaps {
  inner 10px
  outer 25px
}

# @border
default_border pixel 2px
default_floating_border pixel 2px

# @swayfx
corner_radius 12
blur enable
blur_passes 2
blur_radius 5
shadows enable
shadow_blur_radius 18
shadow_color #00000038
default_dim_inactive 0.04

#                       border          bg         text               indicator          child_border
client.focused          $accent-color   $bg-color  $text-color        $accent-color      $accent-color
client.focused_inactive $overlay-bg-color $bg-color $inactive-text-color $overlay-bg-color $overlay-bg-color
client.unfocused        $bg-color       $bg-color  $inactive-text-color $bg-color        $bg-color
client.urgent           $urgent-bg-color $bg-color $urgent-bg-color   $urgent-bg-color   $urgent-bg-color
client.placeholder      $overlay-bg-color $bg-color $text-color       $overlay-bg-color  $overlay-bg-color
